<a href="https://colab.research.google.com/github/ThuanPhong0126/CS114.K21/blob/master/FolioKNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import os

In [0]:
path='drive/My Drive/Colab Notebooks/Folio/Folio Leaf Dataset/Folio Leaf Dataset/Folio'

In [0]:
nhan=os.listdir(os.path.expanduser(path))
nhan

['papaya',
 'vieux garcon',
 'thevetia',
 'sweet olive',
 'star apple',
 'pimento',
 'rose',
 'pomme jacquot',
 'sweet potato',
 'mulberry leaf',
 'eggplant',
 'jackfruit',
 'ketembilla',
 'hibiscus',
 'lychee',
 'geranium',
 'guava',
 'fruitcitere',
 'ficus',
 'duranta gold',
 'croton',
 'bitter orange',
 'betel',
 'beaumier du perou',
 'coeur demoiselle',
 'caricature plant',
 'coffee',
 'chinese guava',
 'chocolate tree',
 'chrysanthemum',
 'barbados cherry',
 'ashanti blood']

In [0]:
FJoin=os.path.join
file=[FJoin(path,f) for f in os.listdir(path)]
file

['drive/My Drive/Colab Notebooks/Folio/Folio Leaf Dataset/Folio Leaf Dataset/Folio/papaya',
 'drive/My Drive/Colab Notebooks/Folio/Folio Leaf Dataset/Folio Leaf Dataset/Folio/vieux garcon',
 'drive/My Drive/Colab Notebooks/Folio/Folio Leaf Dataset/Folio Leaf Dataset/Folio/thevetia',
 'drive/My Drive/Colab Notebooks/Folio/Folio Leaf Dataset/Folio Leaf Dataset/Folio/sweet olive',
 'drive/My Drive/Colab Notebooks/Folio/Folio Leaf Dataset/Folio Leaf Dataset/Folio/star apple',
 'drive/My Drive/Colab Notebooks/Folio/Folio Leaf Dataset/Folio Leaf Dataset/Folio/pimento',
 'drive/My Drive/Colab Notebooks/Folio/Folio Leaf Dataset/Folio Leaf Dataset/Folio/rose',
 'drive/My Drive/Colab Notebooks/Folio/Folio Leaf Dataset/Folio Leaf Dataset/Folio/pomme jacquot',
 'drive/My Drive/Colab Notebooks/Folio/Folio Leaf Dataset/Folio Leaf Dataset/Folio/sweet potato',
 'drive/My Drive/Colab Notebooks/Folio/Folio Leaf Dataset/Folio Leaf Dataset/Folio/mulberry leaf',
 'drive/My Drive/Colab Notebooks/Folio/Folio

In [0]:
import cv2

In [0]:
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
import numpy as np
import glob

In [0]:
images=[]
labels=[]
f=0
h=0

In [0]:
for dir_path in glob.glob("drive/My Drive/Colab Notebooks/Folio/Folio Leaf Dataset/Folio Leaf Dataset/Folio/*"):
    img_label = dir_path.split("/")[-1]
    f+=1
    for img_path in glob.glob(os.path.join(dir_path, "*")):
        img = cv2.imread(img_path)
        img = cv2.resize(img, (800,800))
        h+=1
        #img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        images.append(img)
        labels.append(img_label)

In [0]:
l=set(labels)
l

{'ashanti blood',
 'barbados cherry',
 'beaumier du perou',
 'betel',
 'bitter orange',
 'caricature plant',
 'chinese guava',
 'chocolate tree',
 'chrysanthemum',
 'coeur demoiselle',
 'coffee',
 'croton',
 'duranta gold',
 'eggplant',
 'ficus',
 'fruitcitere',
 'geranium',
 'guava',
 'hibiscus',
 'jackfruit',
 'ketembilla',
 'lychee',
 'mulberry leaf',
 'papaya',
 'pimento',
 'pomme jacquot',
 'rose',
 'star apple',
 'sweet olive',
 'sweet potato',
 'thevetia',
 'vieux garcon'}

In [0]:
h

637

In [0]:
image_arrays=[]
for img in images:
  image=np.array(img,dtype=np.float64)/255
  w,h,d=original_shape=tuple(image.shape)
  image_array=np.reshape(img,(w*h*d))
  image_arrays.append(image_array)

In [0]:
label_array=[]
for i in labels:
  label_array.append(nhan.index(i))
label_array=np.array(label_array)
label_array

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11,
       11, 11, 11, 11, 11

In [0]:
labels=np.array(labels)

In [0]:
labels.shape

(637,)

In [0]:
image_arrays=np.array(image_arrays)
image_arrays.shape

(637, 1920000)

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train,X_test,y_train,y_test=train_test_split(image_arrays,label_array,test_size=0.3,random_state=101)

In [0]:
X_train

array([[237, 232, 233, ..., 175, 176, 174],
       [244, 244, 244, ..., 220, 221, 219],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [217, 224, 233, ..., 224, 235, 243],
       [255, 255, 255, ..., 255, 255, 255],
       [236, 234, 234, ..., 191, 186, 187]], dtype=uint8)

In [0]:
y_train

array([20, 14, 29, 24, 17,  9, 25, 28,  0, 29, 22, 14,  4, 22, 21, 28, 13,
       16, 28,  7, 19,  8, 14,  4,  3, 25, 16, 24, 17, 26, 14,  1, 13, 25,
       16,  5,  9, 31, 26, 17, 19, 29, 14,  3,  2, 22, 10,  5, 27, 13,  8,
       27, 20, 18, 16, 30,  9,  7, 21, 13,  9, 21, 20, 13, 14,  4,  1, 21,
        6, 17, 24, 31,  9, 24,  8,  0, 26,  8,  4, 16, 13, 28,  3, 19,  9,
       10,  2,  3, 24, 24,  2, 30, 10, 21,  7, 22, 22,  8, 28, 20,  2,  6,
        2, 30,  6, 29, 21, 12,  7, 15, 27,  6,  8, 25, 11, 11, 13,  9,  0,
       24, 11, 10,  8,  0, 14,  7, 11, 25, 31,  0,  3,  0, 28,  9, 22,  4,
       26, 25, 30, 20, 22, 10,  0, 17, 31, 13, 28,  8, 15,  7, 29, 15, 23,
       25, 31, 11,  8, 28, 29,  2, 16, 21,  5,  4, 14,  6,  3,  8, 27, 21,
       23,  6, 31, 31, 18, 15,  1, 24,  5, 31, 12, 19,  1, 29, 31, 13,  7,
       10,  1, 14, 22, 16, 10, 22, 18,  6, 21, 21, 20, 29,  5, 27, 29, 24,
       12, 12, 26,  6, 26, 17, 25,  3, 12, 20, 24, 12, 22, 17,  9, 26, 30,
       23, 30, 15, 28,  4

In [0]:
from sklearn.neighbors import KNeighborsClassifier

In [0]:
knn=KNeighborsClassifier(n_neighbors=1,p=2)

In [0]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [0]:
predic=knn.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix,classification_report

In [0]:
print(confusion_matrix(y_test,predic))

[[5 0 0 ... 0 0 0]
 [0 5 0 ... 0 0 0]
 [0 0 5 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 4]]


In [0]:
print(classification_report(y_test,predic))

              precision    recall  f1-score   support

           0       1.00      0.71      0.83         7
           1       0.83      0.62      0.71         8
           2       1.00      1.00      1.00         5
           3       0.60      0.60      0.60         5
           4       0.25      0.33      0.29         3
           5       0.64      1.00      0.78         9
           6       0.60      0.86      0.71         7
           7       0.75      1.00      0.86         6
           8       1.00      1.00      1.00         7
           9       0.33      0.20      0.25         5
          10       0.67      0.29      0.40         7
          11       1.00      0.57      0.73         7
          12       0.71      0.71      0.71         7
          13       0.50      0.75      0.60         4
          14       1.00      0.71      0.83         7
          15       1.00      1.00      1.00         7
          16       0.67      0.89      0.76         9
          17       1.00    